name: slack-approver
description: Custom action to send approval request to Slack from GitHub Actions
author: danshapir
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: plus
  color: green

